---
title: "viz_part_01"
author: "Aaron Mittel"
date: "2022-09-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's import data

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
  weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Let's make a scatterplot

```{r}
ggplot(weather_df, aes(x=tmin, y=tmax)) +
  geom_point()
```

## Let's make the same scatterplot, but different.

```{r}
weather_df %>%
  drop_na() %>%
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point()
```

## Let's keep making the same plot but different.

```{r}
weather_scatterplot =
  weather_df %>%
  drop_na() %>%
  ggplot(aes(x=tmin, y=tmax))

weather_scatterplot +
  geom_point()
```

## Let's fancy this up a bit

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)
```

## Maybe make separate panels.

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

'tmax' vs 'tmin' is boring. Let's spice it up a bit.

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

## Some quick stuff

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y=tmax)) +
  geom_hex()
```


## univariate plots

Histograms, barplots, boxplots, violins...

```{r}
weather_df %>%
  ggplot(aes(x=tmax, fill = name)) +
  geom_histogram(binwidth = 2) +
  facet_grid(. ~ name)
```

```{r}
weather_df %>%
  ggplot(aes(x=tmax, fill = name)) +
  geom_density(alpha = 0.3, adjust = 0.4)
```

```{r}
weather_df %>%
  ggplot(aes(x=name, y=tmax, fill = name)) +
  geom_boxplot()
```

```{r}
weather_df %>%
  ggplot(aes(x=name, y=tmax, fill = name)) +
  geom_violin()
```

OR

```{r}
weather_df %>%
  ggplot(aes(x=tmax, y=name, fill = name)) +
  geom_density_ridges()
```

```{r}
weather_scatterplot =
  weather_df %>%
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_point(aes(size=prcp), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

weather_scatterplot

ggsave(
  "results/weather_scatterplot.pdf", weather_scatterplot,
  width = 8, height = 5)
```

```{r, fig.width = 10}
weather_scatterplot
```

